server:
  port: 443
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 8h
#  ssl:
#    enabled: true
#    key-store-type: "PKCS12"
#    key-store: file:C:\Users\79130\IdeaProjects\VC\src\main\resources\keystore.p12
#    key-store-password: ${SSL_KEY_PASSWORD:Edcvt12!}
#    key-alias: vs-sport

  logging:
    charset:
      console: UTF-8
      file: UTF-8

spring:
  thymeleaf:
    encoding: UTF-8
    mode: HTML
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: ${MAIL:shuffle2149@gmail.com}
    password: ${MAIL_PASSWORD:frqwptlnpssetliw}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
  liquibase:
    change-log: "db/changelog/db.changelog-master.xml"
    enabled: true
  datasource:
    url: "jdbc:postgresql://localhost:5439/ttvc"
    username: ${DB_USERNAME:shuffle}
    password: ${DB_PASSWORD:shuffle}

storage:
  location: ${STORAGE_LOCATION:./storage}

springdoc:
  show-login-endpoint: true

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: "jdbc:postgresql://localhost:5432/ttvc"
    username:  ${PROD_DB_USERNAME:shuffle}
    password:  ${PROD_DB_PASSWORD:rfvby}

server:  # ← server на уровне профиля prod
  port: 443
  ssl:   # ← ssl ВНУТРИ server
    enabled: true
    key-store-type: "PKCS12"
    key-store: file:/opt/vc-app/keystore.p12
    key-store-password: ${SSL_KEY_PASSWORD:Edcvt12!}
    key-alias: vs-sport

storage:
  location: /opt/vc-app/storage

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:postgresql://localhost:5439/ttvc"
    username: ${DEV_DB_USERNAME:shuffle}
    password: ${DEV_DB_PASSWORD:shuffle}

storage:
  location: ./storage
server:
  port: 443
#  ssl:
#    enabled: false
#    key-store-type: "PKCS12"
#    key-store: "classpath:keystore.p12"
#    key-store-password: ${KEYSTORE_PASSWORD:shuffle}
#    key-alias: "tomcat"