INSERT INTO tournament (
    id,
    title,
    date,
    time_tour,
    address_id,
    amount_players,
    VERSION,
    created_by,
    created_date,
    last_modified_by,
    last_modified_date,
    status,
    RESULT_TOUR,
    INFO,
    video_url_cam1,
    video_url_cam2
) VALUES (
             0,
             'Major League TT',
             '2026-06-06',
             '24/7',
             2,
             32,
             1,
             'admin',
             '2022-09-14 07:52:54'::TIMESTAMP,
             'admin',
             '2022-09-19 06:18:18'::TIMESTAMP,
             'ACTIVE'::VARCHAR,
             NULL,
             NULL,
             'https://cdn.fast.jwp.services/v1/channel/0_zetjamzo_Hplllvlc/manifest/3.m3u8',
             'http://localhost:1984/stream.html?src=cam1'
         );