CREATE TABLE IF NOT EXISTS tournament (
                                          ID BIGSERIAL NOT NULL PRIMARY KEY,
                                          title VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    time_tour VARCHAR(255) NOT NULL,
    address_id BIGINT NOT NULL,
    amount_players BIGINT NOT NULL,
    VERSION INT DEFAULT 0 NOT NULL,
    CREATED_BY VARCHAR(255) NULL,
    CREATED_DATE TIMESTAMP NULL,
    LAST_MODIFIED_BY VARCHAR(255) NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL,
    STATUS VARCHAR(30) DEFAULT 'ACTIVE' NOT NULL,
    RESULT_TOUR VARCHAR(2000) NULL,
    INFO VARCHAR(2000) NULL,
    VIDEO_URL_CAM1 VARCHAR(2000) NULL,
    VIDEO_URL_CAM2 VARCHAR(2000) NULL
    );