CREATE TABLE IF NOT EXISTS CONFIRMATION_CODE(
    ID   BIGSERIAL    NOT NULL PRIMARY KEY,
    CODE VARCHAR(255) NOT NULL,
    UNIQUE (CODE),
    USER_ID BIGSERIAL,
    CONSTRAINT ACCOUNT_USER_FOREIGN_KEY
    FOREIGN KEY (USER_ID)
    REFERENCES ACCOUNT_USER (ID)
);
