CREATE TABLE IF NOT EXISTS address (
                                       ID BIGSERIAL NOT NULL PRIMARY KEY,
                                       country VARCHAR(512) DEFAULT NULL,
    city VARCHAR(512) NOT NULL,
    street VARCHAR(512) NOT NULL,
    house DECIMAL(10,2) DEFAULT NULL,
    VERSION INT NOT NULL DEFAULT 0,
    CREATED_BY VARCHAR(255) DEFAULT NULL,
    CREATED_DATE TIMESTAMP NULL DEFAULT NULL,
    LAST_MODIFIED_BY VARCHAR(255) DEFAULT NULL,
    LAST_MODIFIED_DATE TIMESTAMP NULL DEFAULT NULL
    );